//These are in REVERSE CHRONOLOGICAL ORDER, unlike everything else which is in alphabetical order
//Reason being that I think it will be easier over time to just keep adding entries to the top...

var item_tags = [
	["2021","2022","2023","2024","2025"],
	["January","February","March","April","May","June","July","August","September","October","November","December"],
	["New release","Update","Announcement","Event","Website update","Dev musings"],
	//Announcement: things like the wiki opening, translation projects finishing, etc...
	//Maybe should make event announcements a separate tag too...? or just an event tag? hm
	["Yearly summary","Advent calendar"],
	["Mirror"],
	//I think it would be cool to have tags for like... "deconstructing my own work", but I'd need to come up with a more succinct tag, and also I should at least make one post like that before I add a tag lol
	//Should I word count...? hm
]

//Note to self: the "latest" is for if something gets a MAJOR REVISION, not just typos and such
//Things like an error catastrophagus
var item_details = [
	
	// {
		// name: "",
		// release: "",
		// dupeindex: "00",
		// latest: null,
		// page: "",
		// blurb: "",
		// tags: [],
	// },
	{
		name: "Function RoboText",
		release: "2025-07-28",
		dupeindex: "02",
		latest: null,
		page: "2025-07-28_robotext_function.html",
		blurb: "Release of a new function: RoboText. This function takes a dialogue string and outputs it in chunks of 3 characters at a time, with various options to adjust it. It's intended to give text a more robotic feel.",
		tags: ["2025","July","New release"],
	},
	{
		name: "ATM Machine v2.0.2",
		release: "2025-07-28",
		dupeindex: "01",
		latest: null,
		page: "2025-07-28_atm_machine_v2.0.2.html",
		blurb: "An update to ATM Machine that makes the normal ATM text have a more robotic feel, as well as various other minor changes.",
		tags: ["2025","July","Update"],
	},
	{
		name: "Ye Olde Cursed Tower v1.0.1",
		release: "2025-07-28",
		dupeindex: "00",
		latest: null,
		page: "2025-07-28_ye_olde_cursed_tower_v1.0.1.html",
		blurb: "An update to Ye Olde Cursed Tower to smooth out the jam jankiness and add more dialogue, as well as other minor features.",
		tags: ["2025","July","Update"],
	},
	{
		name: "Xander's Refuge v1.0.4",
		release: "2025-07-25",
		dupeindex: "00",
		latest: null,
		page: "2025-07-25_xanders_refuge_v1.0.4.html",
		blurb: "A small update to Xander's Refuge (both the original version and the Aosora port) with some minor changes and code cleanup.",
		tags: ["2025","July","Update"],
	},
	{
		name: "Aughost 2025 announcement",
		release: "2025-07-24",
		dupeindex: "00",
		latest: "2025-07-28",
		page: "2025-07-24_aughost_2025_announcement.html",
		blurb: "Aughost 2025 will be happening soon! See the event's page for the guidelines.",
		tags: ["2025","July","Announcement","Event"],
	},
	{
		name: "Permissions page now available",
		release: "2025-07-15",
		dupeindex: "00",
		latest: null,
		page: "2025-07-15_permissions_page_now_available.html",
		blurb: "A new page has been added to the website, detailing permissions for how my various different works should be handled.",
		tags: ["2025","July","Website update"],
	},
	{
		name: "Hoard of Shinies v1.0.6",
		release: "2025-07-10",
		dupeindex: "00",
		latest: null,
		page: "2025-07-10_hoard_of_shinies_v1.0.6.html",
		blurb: "A small update with some additional settings for Hoard of Shinies.",
		tags: ["2025","July","Update"],
	},
	{
		name: "Doodle Daydreams v1.0.1",
		release: "2025-06-30",
		dupeindex: "00",
		latest: null,
		page: "2025-06-30_doodle_daydreams_v1.0.1.html",
		blurb: "A small patch for Doodle Daydreams to iron out the jam jank.",
		tags: ["2025","June","Update"],
	},
	{
		name: "Ye Olde Soul Spell v1.0.0",
		release: "2025-06-26",
		dupeindex: "00",
		latest: null,
		page: "2025-06-26_ye_olde_soul_spell_v1.0.0.html",
		blurb: "Release of a new balloon: Ye Olde Soul Spell. A spell themed balloon with a variety of colors and a few patterns. It's also round!",
		tags: ["2025","June","New release"],
	},
	{
		name: "Ye Olde Cursed Tower v1.0.0",
		release: "2025-06-26",
		dupeindex: "00",
		latest: null,
		page: "2025-06-26_ye_olde_cursed_tower_v1.0.0.html",
		blurb: "Release of a new ghost: Ye Olde Cursed Tower. An evil wizard sits atop a tower, collecting souls... for what purpose? Nobody is sure. What will happen to the people trapped within the tower's walls? ... Well, that's up to you, since you are that wizard! Have fun.",
		tags: ["2025","June","New release"],
	},
	{
		name: "Doodle Daydreams v1.0.0",
		release: "2025-06-21",
		dupeindex: "00",
		latest: null,
		page: "2025-06-21_doodle_daydreams_v1.0.0.html",
		blurb: "Release of a new ghost: Doodle Daydreams. A poseable doll to dress up and daydream with. What worlds will your mind take you to...?",
		tags: ["2025","June","New release"],
	},
	{
		name: "GroupDigits function",
		release: "2025-06-20",
		dupeindex: "00",
		latest: null,
		page: "2025-06-20_groupdigits_function.html",
		blurb: "Release of a new function: GroupDigits. This function takes an integer or real number and outputs it as a string with commas as thousands separators.",
		tags: ["2025","June","New release"],
	},
	{
		name: "Weather Station v1.1.0",
		release: "2025-06-18",
		dupeindex: "00",
		latest: null,
		page: "2025-06-18_weather_station_v1.1.0.html",
		blurb: "A major update for Weather Station to overhaul various parts of the code, deprecate some references for privacy concerns, add a thumbnail, and add some new options for formatting the date and time.",
		tags: ["2025","June","Update"],
	},
	{
		name: "Weather Station v1.0.5",
		release: "2025-06-10",
		dupeindex: "00",
		latest: null,
		page: "2025-06-10_weather_station_v1.0.5.html",
		blurb: "A small patch for Weather Station to fix some issues while offline.",
		tags: ["2025","June","Update"],
	},
	{
		name: "Blog grand opening",
		release: "2025-05-22",
		dupeindex: "01",
		latest: null,
		page: "2025-05-22_blog_grand_opening.html",
		blurb: "The grand opening of this blog in its full and proper form. Everything before this point was created as a blog post without a home.",
		tags: ["2025","May","Announcement","Website update"],
	},
	{
		name: "My ghost development history",
		release: "2025-05-22",
		dupeindex: "00",
		latest: null,
		page: "2025-05-22_my_ghost_development_history.html",
		blurb: "My history as a ghost developer, cataloguing as many releases and updates as I could find from before the launch of this blog.",
		tags: ["2025","May","Dev musings"],
	},
	{
		name: "Summary of 2024 in the Ukagaka Dream Team (Advent calendar 2024)",
		release: "2024-12-23",
		dupeindex: "00",
		latest: null,
		page: "2024-12-23_advent_calendar_summary_of_2024.html",
		blurb: "A summary of events and other important happenings in the Ukagaka Dream Team during 2024.",
		tags: ["2024","December","Yearly summary","Advent calendar"],
	},
	{
		name: "Spectre: What, why, and how (Advent calendar 2024)",
		release: "2024-12-22",
		dupeindex: "00",
		latest: null,
		page: "2024-12-22_advent_calendar_spectre.html",
		blurb: "An article describing the plugin <a href='../plugin/spectre.html'>Spectre</a>, and also exploring the development process and various considerations we had after making it.",
		tags: ["2024","December","Dev musings","Advent calendar"],
	},
	{
		name: "Needle Dog mirror",
		release: "2024-11-11",
		dupeindex: "00",
		latest: null,
		page: "2024-11-11_needle_dog_mirror.html",
		blurb: "A mirror download of the shell Needle Dog, created with permission from its author since the original download went down.",
		tags: ["2024","November","Mirror"],
	},
	{
		name: "FLELE mirror",
		release: "2024-10-13",
		dupeindex: "00",
		latest: null,
		page: "2024-10-13_flele_mirror.html",
		blurb: "A mirror download of FLELE, created based on permissions given on FLELE's distribution site. It may be helpful for those who cannot access FLELE's page.",
		tags: ["2024","October","Mirror"],
	},
	{
		name: "Summary of 2023 in the Ukagaka Dream Team (Advent calendar 2023)",
		release: "2023-12-23",
		dupeindex: "00",
		latest: null,
		page: "2023-12-23_advent_calendar_summary_of_2023.html",
		blurb: "A summary of events and other important happenings in the Ukagaka Dream Team during 2023.",
		tags: ["2023","December","Yearly summary","Advent calendar"],
	},
	{
		name: "Ukadoc English translation completed (Advent calendar 2023)",
		release: "2023-12-22",
		dupeindex: "00",
		latest: null,
		page: "2023-12-22_advent_calendar_ukadoc_english_translation.html",
		blurb: "An announcement of the completion of the Ukadoc English translation project.",
		tags: ["2023","December","Announcement","Advent calendar"],
	},
	{
		name: "YAYA Fundamentals guide release (Advent calendar 2022)",
		release: "2022-12-24",
		dupeindex: "00",
		latest: null,
		page: "2022-12-24_advent_calendar_yaya_fundamentals_release.html",
		blurb: "The release of an extensive guide to YAYA in English, called YAYA Fundamentals.",
		tags: ["2022","December","New release","Advent calendar"],
	},
	{
		name: "Ukagaka Dream Team Wiki release (Advent calendar 2022)",
		release: "2022-12-23",
		dupeindex: "00",
		latest: null,
		page: "2022-12-23_advent_calendar_wiki_release.html",
		blurb: "A release announcement for the Ukagaka Dream Team Wiki, which is now publicly available with almost all the pages up to this point filled in.",
		tags: ["2022","December","Announcement","Advent calendar"],
	},
	{
		name: "How to write a Needle (Advent calendar 2022)",
		release: "2022-12-19",
		dupeindex: "00",
		latest: null,
		page: "2022-12-19_advent_calendar_how_to_write_a_needle.html",
		blurb: "A recounting of the process of writing <a href='../ghost/needle.html'>Needle</a> for Ghost Jam 2022, and how it changed the way I think about writing ghosts since then.",
		tags: ["2022","December","Dev musings","Advent calendar"],
	},
	{
		name: "I've spent a ridiculous amount of time thinking about probabilities: An ukagaka developer's struggle for probability perfection (Advent calendar 2021)",
		release: "2021-12-12",
		dupeindex: "00",
		latest: null,
		page: "2021-12-12_advent_calendar_probabilities.html",
		blurb: "An exploration of probabilities in YAYA, and how I eventually managed to overcome various issues to attain a perfect result (with the help of developers who knew what they were doing much better than I did!)",
		tags: ["2021","December","Dev musings","Advent calendar"],
	},
]