//These are in REVERSE CHRONOLOGICAL ORDER, unlike everything else which is in alphabetical order
//Reason being that I think it will be easier over time to just keep adding entries to the top...

var item_tags = [
	["2021","2022","2023","2024","2025"],
	["January","February","March","April","May","June","July","August","September","October","November","December"],
	["Ghost","Shell","Freeshell","Balloon","Template","Calendar skin","SAORI","Plugin","Tool","Guide","Function","Minigame","Free asset","Misc","Event"],
	["New release","Update","Announcement","Website update","Dev musings"],
	//Announcement: things like the wiki opening, translation projects finishing, etc...
	//Maybe should make event announcements a separate tag too...? or just an event tag? hm
	["Yearly summary","Advent calendar"],
	["Mirror"],
	//I think it would be cool to have tags for like... "deconstructing my own work", but I'd need to come up with a more succinct tag, and also I should at least make one post like that before I add a tag lol
	//Should I word count...? hm
]

//Note to self: the "latest" is for if something gets a MAJOR REVISION, not just typos and such
//Things like an error catastrophagus
var item_details = [
	
	// {
		// name: "",
		// release: "",
		// dupeindex: "00",
		// latest: null,
		// page: "",
		// blurb: "",
		// tags: [],
	// },
	{
		name: "FLUX v2.0.0",
		release: "2025-11-23",
		dupeindex: "00",
		latest: null,
		page: "2025-11-23_flux_v2.0.0.html",
		blurb: "A major overhaul for <a href='../ghost/flux.html'>FLUX</a> code, bringing many new features to the music player, adding a Spanish translation, and deprecating several old functions.",
		tags: ["2025","November","Ghost","Update"],
	},
	{
		name: "Music player v2.0.4",
		release: "2025-11-22",
		dupeindex: "00",
		latest: null,
		page: "2025-11-22_music_player_v2.0.4.html",
		blurb: "An update to my <a href='../function/index.html#music_player'>music player</a> code, fixing several bugs, as well as bringing some formatting cleanup and other small improvements.",
		tags: ["2025","November","Function","Update"],
	},
	{
		name: "Needloon (readable) v1.0.1",
		release: "2025-11-13",
		dupeindex: "01",
		latest: null,
		page: "2025-11-13_needloon_readable_v1.0.1.html",
		blurb: "An update to the shell <a href='../balloon/needloon_readable.html'>Needloon (readable)</a>, fixing a longstanding issue with visited anchors having the wrong shadow style.",
		tags: ["2025","November","Balloon","Update"],
	},
	{
		name: "Corkscrew v1.0.1",
		release: "2025-11-13",
		dupeindex: "00",
		latest: null,
		page: "2025-11-13_corkscrew_v1.0.1.html",
		blurb: "An update to the shell <a href='../shell/corkscrew.html'>Corkscrew</a>, adding several new colors and some other options for variation.",
		tags: ["2025","November","Shell","Update"],
	},
	{
		name: "Needle Day 2025",
		release: "2025-11-11",
		dupeindex: "00",
		latest: null,
		page: "2025-11-11_needle_day_2025.html",
		blurb: "Needle Day 2025 has arrived, bringing with it <a href='../ghost/needle.html'>Needle</a> v1.1.5 and 11 new Needle shells.",
		tags: ["2025","November","Ghost","Shell","Event","New release","Update"],
	},
	{
		name: "Wanted: Dead, Alive, or Other v1.0.1",
		release: "2025-10-29",
		dupeindex: "00",
		latest: null,
		page: "2025-10-29_wanted_dead_alive_or_other_v1.0.1.html",
		blurb: "An update to <a href='../ghost/wanted_dead_alive_or_other.html'>Wanted: Dead, Alive, or Other</a> has been released, smoothing out jam bugs and adding some new content.",
		tags: ["2025","October","Ghost","Update"],
	},
	{
		name: "SSP Angel v1.1.3",
		release: "2025-10-05",
		dupeindex: "00",
		latest: null,
		page: "2025-10-05_ssp_angel_v1.1.3.html",
		blurb: "A minor update to <a href='../ghost/ssp_angel.html'>SSP Angel</a> has been released, updating various terms to match the new SSP English translations, and clarifying or correcting other information. A small amount of new idle dialogue has been added as well.",
		tags: ["2025","October","Ghost","Update"],
	},
	{
		name: "Wanted: Dead, Alive, or Other v1.0.0",
		release: "2025-09-26",
		dupeindex: "01",
		latest: null,
		page: "2025-09-26_wanted_dead_alive_or_other_v1.0.0.html",
		blurb: "Release of a new ghost: <a href='../ghost/wanted_dead_alive_or_other.html'>Wanted: Dead, Alive, or Other</a>. Necromancy is tiring work, mostly because it takes so long to interview candidates and select the best ones. But it is a necessary process, otherwise research results will be chaotic and rather useless... Best get to it, then.",
		tags: ["2025","September","Ghost","New release"],
	},
	{
		name: "EncodeMorse &amp; DecodeMorse functions",
		release: "2025-09-26",
		dupeindex: "00",
		latest: null,
		page: "2025-09-26_encodemorse_decodemorse_functions.html",
		blurb: "Release of a new set of functions: <a href='../function/index.html#encodemorse_decodemorse'>EncodeMorse &amp; DecodeMorse</a>. These functions can change text to and from morse code, and may be customized to add new codes.",
		tags: ["2025","September","Function","New release"],
	},
	{
		name: "Hydrate v2.0.4",
		release: "2025-09-17",
		dupeindex: "00",
		latest: null,
		page: "2025-09-17_hydrate_v2.0.4.html",
		blurb: "A major update to <a href='../ghost/hydrate.html'>Hydrate</a> has been released, with a final breaking change to the stat share event, finer timing control of the auto shell/dressup changes, and legacy content now toggleable.",
		tags: ["2025","September","Ghost","Update"],
	},
	{
		name: "Hydrate v2.0.3",
		release: "2025-09-16",
		dupeindex: "00",
		latest: null,
		page: "2025-09-16_hydrate_v2.0.3.html",
		blurb: "A major update to <a href='../ghost/hydrate.html'>Hydrate</a> has been released, bringing options to let Hydrate randomly change shells/dressups for you at configurable intervals, and more.",
		tags: ["2025","September","Ghost","Update"],
	},
	{
		name: "Hydrate v2.0.2",
		release: "2025-09-15",
		dupeindex: "01",
		latest: null,
		page: "2025-09-15_hydrate_v2.0.2.html",
		blurb: "A minor update to <a href='../ghost/hydrate.html'>Hydrate</a> has been released, bringing some new quality of life changes and cleaner code.",
		tags: ["2025","September","Ghost","Update"],
	},
	{
		name: "FormatLinks updated",
		release: "2025-09-15",
		dupeindex: "00",
		latest: null,
		page: "2025-09-15_formatlinks_updated.html",
		blurb: "An update to the function <a href='../function/index.html#formatlinks'>FormatLinks</a>, cleaning up the code and making it not rely on compatible.dic.",
		tags: ["2025","September","Function","Update"],
	},
	{
		name: "Hydrate v2.0.1",
		release: "2025-09-14",
		dupeindex: "00",
		latest: null,
		page: "2025-09-14_hydrate_v2.0.1.html",
		blurb: "A major update to <a href='../ghost/hydrate.html'>Hydrate</a> has been released, with some breaking changes to the stat share event that was introduced in the previous update, as well as new features and bug fixes.",
		tags: ["2025","September","Ghost","Update"],
	},
	{
		name: "Hydrate v2.0.0",
		release: "2025-09-13",
		dupeindex: "00",
		latest: null,
		page: "2025-09-13_hydrate_v2.0.0.html",
		blurb: "A major update to <a href='../ghost/hydrate.html'>Hydrate</a> has been released, kicking off a long-overdue overhaul. <b>This update includes deprecation of some old functions.</b>",
		tags: ["2025","September","Ghost","Update"],
	},
	{
		name: "Aughost 2025 afterword",
		release: "2025-09-01",
		dupeindex: "00",
		latest: null,
		page: "2025-09-01_aughost_2025_afterword.html",
		blurb: "<a href='../event/aughost_2025.html'>Aughost 2025</a> has ended! Some brief commentary at the end of the event.",
		tags: ["2025","September","Event"],
	},
	{
		name: "8/20 Hydrate Shell Jam afterword",
		release: "2025-08-23",
		dupeindex: "00",
		latest: null,
		page: "2025-08-23_8_20_hydrate_shell_jam_afterword.html",
		blurb: "The <a href='../event/8_20_hydrate_shell_jam_2025_results.html'>results of 8/20 Hydrate Shell Jam 2025</a> are here! A few thoughts after tying up the event.",
		tags: ["2025","August","Event"],
	},
	{
		name: "Stock Pot v1.0.0",
		release: "2025-08-21",
		dupeindex: "01",
		latest: null,
		page: "2025-08-21_stock_pot_v1.0.0.html",
		blurb: "Release of a new <a href='../ghost/hydrate.html'>Hydrate</a> shell, <a href='../shell/stock_pot.html'>Stock Pot</a>. A stock pot with dressups for a lid and steam!",
		tags: ["2025","August","Shell","New release"],
	},
	{
		name: "8/20 Hydrate Shell Jam 2025 has ended",
		release: "2025-08-21",
		dupeindex: "00",
		latest: null,
		page: "2025-08-21_8_20_hydrate_shell_jam_2025_has_ended.html",
		blurb: "<a href='../event/8_20_hydrate_shell_jam_2025_rules.html'>8/20 Hydrate Shell Jam 2025</a> has ended! There is a 1 hour grace period to finish submissions before the form closes.",
		tags: ["2025","August","Event"],
	},
	{
		name: "Stratospheric Delivery v1.0.0",
		release: "2025-08-20",
		dupeindex: "02",
		latest: null,
		page: "2025-08-20_stratospheric_delivery_v1.0.0.html",
		blurb: "Release of a new <a href='../ghost/hydrate.html'>Hydrate</a> shell, <a href='../shell/stratospheric_delivery.html'>Stratospheric Delivery</a>. A free-floating cloud with dressups for rain in various colors, and different colors of cloud!",
		tags: ["2025","August","Shell","New release"],
	},
	{
		name: "Leaky Pipe v1.0.0",
		release: "2025-08-20",
		dupeindex: "01",
		latest: null,
		page: "2025-08-20_leaky_pipe_v1.0.0.html",
		blurb: "Release of a new <a href='../ghost/hydrate.html'>Hydrate</a> shell, <a href='../shell/leaky_pipe.html'>Leaky Pipe</a>. A pipe that sticks to the top of the screen and drops down liquid occasionally!",
		tags: ["2025","August","Shell","New release"],
	},
	{
		name: "8/20 Hydrate Shell Jam 2025 has begun",
		release: "2025-08-20",
		dupeindex: "00",
		latest: null,
		page: "2025-08-20_8_20_hydrate_shell_jam_2025_has_begun.html",
		blurb: "<a href='../event/8_20_hydrate_shell_jam_2025_rules.html'>8/20 Hydrate Shell Jam 2025</a> has begun!",
		tags: ["2025","August","Event"],
	},
	{
		name: "8/20 Hydrate Shell Jam 2025 announcement",
		release: "2025-08-13",
		dupeindex: "00",
		latest: null,
		page: "2025-08-13_8_20_hydrate_shell_jam_2025_announcement.html",
		blurb: "<a href='../event/8_20_hydrate_shell_jam_2025_rules.html'>8/20 Hydrate Shell Jam 2025</a> will be happening soon! See the event's page for the rules and timeframe.",
		tags: ["2025","August","Event"],
	},
	{
		name: "ChunkText function",
		release: "2025-07-28",
		dupeindex: "02",
		latest: null,
		page: "2025-07-28_chunktext_function.html",
		blurb: "Release of a new function: <a href='../function/index.html#chunktext'>ChunkText</a>. This function takes a dialogue string and outputs it in chunks of 3 characters at a time, with various options to adjust it. It's intended to give text a more robotic feel.",
		tags: ["2025","July","Function","New release"],
	},
	{
		name: "ATM Machine v2.0.2",
		release: "2025-07-28",
		dupeindex: "01",
		latest: null,
		page: "2025-07-28_atm_machine_v2.0.2.html",
		blurb: "An update to <a href='../ghost/atm_machine.html'>ATM Machine</a> that makes the normal ATM text have a more robotic feel, as well as various other minor changes.",
		tags: ["2025","July","Ghost","Update"],
	},
	{
		name: "Ye Olde Cursed Tower v1.0.1",
		release: "2025-07-28",
		dupeindex: "00",
		latest: null,
		page: "2025-07-28_ye_olde_cursed_tower_v1.0.1.html",
		blurb: "An update to <a href='../ghost/ye_olde_cursed_tower.html'>Ye Olde Cursed Tower</a> to smooth out the jam jankiness and add more dialogue, as well as other minor features.",
		tags: ["2025","July","Ghost","Update"],
	},
	{
		name: "Xander's Refuge v1.0.4",
		release: "2025-07-25",
		dupeindex: "00",
		latest: null,
		page: "2025-07-25_xanders_refuge_v1.0.4.html",
		blurb: "A small update to <a href='../ghost/xanders_refuge.html'>Xander's Refuge</a> (both the original version and the <a href='../ghost/xanders_refuge_aosora.html'>Aosora port</a>) with some minor changes and code cleanup.",
		tags: ["2025","July","Ghost","Update"],
	},
	{
		name: "Aughost 2025 announcement",
		release: "2025-07-24",
		dupeindex: "00",
		latest: "2025-07-28",
		page: "2025-07-24_aughost_2025_announcement.html",
		blurb: "<a href='../event/aughost_2025.html'>Aughost 2025</a> will be happening soon! See the event's page for the guidelines.",
		tags: ["2025","July","Event"],
	},
	{
		name: "Permissions page now available",
		release: "2025-07-15",
		dupeindex: "00",
		latest: null,
		page: "2025-07-15_permissions_page_now_available.html",
		blurb: "A new page has been added to the website, detailing permissions for how my various different works should be handled.",
		tags: ["2025","July","Website update"],
	},
	{
		name: "Hoard of Shinies v1.0.6",
		release: "2025-07-10",
		dupeindex: "00",
		latest: null,
		page: "2025-07-10_hoard_of_shinies_v1.0.6.html",
		blurb: "A small update with some additional settings for <a href='../ghost/hoard_of_shinies.html'>Hoard of Shinies</a>.",
		tags: ["2025","July","Ghost","Update"],
	},
	{
		name: "Doodle Daydreams v1.0.1",
		release: "2025-06-30",
		dupeindex: "00",
		latest: null,
		page: "2025-06-30_doodle_daydreams_v1.0.1.html",
		blurb: "A small patch for <a href='../ghost/doodle_daydreams.html'>Doodle Daydreams</a> to iron out the jam jank.",
		tags: ["2025","June","Ghost","Update"],
	},
	{
		name: "Ye Olde Soul Spell v1.0.0",
		release: "2025-06-26",
		dupeindex: "00",
		latest: null,
		page: "2025-06-26_ye_olde_soul_spell_v1.0.0.html",
		blurb: "Release of a new balloon: <a href='../balloon/ye_olde_soul_spell.html'>Ye Olde Soul Spell</a>. A spell themed balloon with a variety of colors and a few patterns. It's also round!",
		tags: ["2025","June","Balloon","New release"],
	},
	{
		name: "Ye Olde Cursed Tower v1.0.0",
		release: "2025-06-26",
		dupeindex: "00",
		latest: null,
		page: "2025-06-26_ye_olde_cursed_tower_v1.0.0.html",
		blurb: "Release of a new ghost: <a href='../ghost/ye_olde_cursed_tower.html'>Ye Olde Cursed Tower</a>. An evil wizard sits atop a tower, collecting souls... for what purpose? Nobody is sure. What will happen to the people trapped within the tower's walls? ... Well, that's up to you, since you are that wizard! Have fun.",
		tags: ["2025","June","Ghost","New release"],
	},
	{
		name: "Doodle Daydreams v1.0.0",
		release: "2025-06-21",
		dupeindex: "00",
		latest: null,
		page: "2025-06-21_doodle_daydreams_v1.0.0.html",
		blurb: "Release of a new ghost: <a href='../ghost/doodle_daydreams.html'>Doodle Daydreams</a>. A poseable doll to dress up and daydream with. What worlds will your mind take you to...?",
		tags: ["2025","June","Ghost","New release"],
	},
	{
		name: "GroupDigits function",
		release: "2025-06-20",
		dupeindex: "00",
		latest: null,
		page: "2025-06-20_groupdigits_function.html",
		blurb: "Release of a new function: <a href='../function/index.html#groupdigits'>GroupDigits</a>. This function takes an integer or real number and outputs it as a string with commas as thousands separators.",
		tags: ["2025","June","Function","New release"],
	},
	{
		name: "Weather Station v1.1.0",
		release: "2025-06-18",
		dupeindex: "00",
		latest: null,
		page: "2025-06-18_weather_station_v1.1.0.html",
		blurb: "A major update for <a href='../plugin/weather_station.html'>Weather Station</a> to overhaul various parts of the code, deprecate some references for privacy concerns, add a thumbnail, and add some new options for formatting the date and time.",
		tags: ["2025","June","Plugin","Update"],
	},
	{
		name: "Weather Station v1.0.5",
		release: "2025-06-10",
		dupeindex: "00",
		latest: null,
		page: "2025-06-10_weather_station_v1.0.5.html",
		blurb: "A small patch for <a href='../plugin/weather_station.html'>Weather Station</a> to fix some issues while offline.",
		tags: ["2025","June","Plugin","Update"],
	},
	{
		name: "Blog grand opening",
		release: "2025-05-22",
		dupeindex: "01",
		latest: null,
		page: "2025-05-22_blog_grand_opening.html",
		blurb: "The grand opening of this blog in its full and proper form. Everything before this point was created as a blog post without a home.",
		tags: ["2025","May","Announcement","Website update"],
	},
	{
		name: "My ghost development history",
		release: "2025-05-22",
		dupeindex: "00",
		latest: null,
		page: "2025-05-22_my_ghost_development_history.html",
		blurb: "My history as a ghost developer, cataloguing as many releases and updates as I could find from before the launch of this blog.",
		tags: ["2025","May","Dev musings"],
	},
	{
		name: "Summary of 2024 in the Ukagaka Dream Team (Advent calendar 2024)",
		release: "2024-12-23",
		dupeindex: "00",
		latest: null,
		page: "2024-12-23_advent_calendar_summary_of_2024.html",
		blurb: "A summary of events and other important happenings in the Ukagaka Dream Team during 2024.",
		tags: ["2024","December","Yearly summary","Advent calendar"],
	},
	{
		name: "Spectre: What, why, and how (Advent calendar 2024)",
		release: "2024-12-22",
		dupeindex: "00",
		latest: null,
		page: "2024-12-22_advent_calendar_spectre.html",
		blurb: "An article describing the plugin <a href='../plugin/spectre.html'>Spectre</a>, and also exploring the development process and various considerations we had after making it.",
		tags: ["2024","December","Dev musings","Advent calendar"],
	},
	{
		name: "Needle Dog mirror",
		release: "2024-11-11",
		dupeindex: "00",
		latest: null,
		page: "2024-11-11_needle_dog_mirror.html",
		blurb: "A mirror download of the shell <a href='https://ukagakadreamteam.com/wiki/shell/needle/needle_dog'>Needle Dog</a>, created with permission from its author since the original download went down.",
		tags: ["2024","November","Mirror"],
	},
	{
		name: "FLELE mirror",
		release: "2024-10-13",
		dupeindex: "00",
		latest: null,
		page: "2024-10-13_flele_mirror.html",
		blurb: "A mirror download of FLELE, created based on permissions given on <a href='http://navy.nm.land.to/ukgk/flele/'>FLELE's distribution site</a>. It may be helpful for those who cannot access FLELE's page.",
		tags: ["2024","October","Mirror"],
	},
	{
		name: "Summary of 2023 in the Ukagaka Dream Team (Advent calendar 2023)",
		release: "2023-12-23",
		dupeindex: "00",
		latest: null,
		page: "2023-12-23_advent_calendar_summary_of_2023.html",
		blurb: "A summary of events and other important happenings in the Ukagaka Dream Team during 2023.",
		tags: ["2023","December","Yearly summary","Advent calendar"],
	},
	{
		name: "Ukadoc English translation completed (Advent calendar 2023)",
		release: "2023-12-22",
		dupeindex: "00",
		latest: null,
		page: "2023-12-22_advent_calendar_ukadoc_english_translation.html",
		blurb: "An announcement of the completion of the <a href='https://ukagakadreamteam.github.io/ukadoc/manual/index.html'>Ukadoc English translation</a> project.",
		tags: ["2023","December","Announcement","Advent calendar"],
	},
	{
		name: "YAYA Fundamentals guide release (Advent calendar 2022)",
		release: "2022-12-24",
		dupeindex: "00",
		latest: null,
		page: "2022-12-24_advent_calendar_yaya_fundamentals_release.html",
		blurb: "The release of an extensive guide to YAYA in English, called <a href='https://zichqec.github.io/YAYA_Fundamentals/'>YAYA Fundamentals</a>.",
		tags: ["2022","December","New release","Advent calendar"],
	},
	{
		name: "Ukagaka Dream Team Wiki release (Advent calendar 2022)",
		release: "2022-12-23",
		dupeindex: "00",
		latest: null,
		page: "2022-12-23_advent_calendar_wiki_release.html",
		blurb: "A release announcement for the <a href='https://ukagakadreamteam.com/wiki/home'>Ukagaka Dream Team Wiki</a>, which is now publicly available with almost all the pages up to this point filled in.",
		tags: ["2022","December","Announcement","Advent calendar"],
	},
	{
		name: "How to write a Needle (Advent calendar 2022)",
		release: "2022-12-19",
		dupeindex: "00",
		latest: null,
		page: "2022-12-19_advent_calendar_how_to_write_a_needle.html",
		blurb: "A recounting of the process of writing <a href='../ghost/needle.html'>Needle</a> for Ghost Jam 2022, and how it changed the way I think about writing ghosts since then.",
		tags: ["2022","December","Dev musings","Advent calendar"],
	},
	{
		name: "I've spent a ridiculous amount of time thinking about probabilities: An ukagaka developer's struggle for probability perfection (Advent calendar 2021)",
		release: "2021-12-12",
		dupeindex: "00",
		latest: null,
		page: "2021-12-12_advent_calendar_probabilities.html",
		blurb: "An exploration of probabilities in YAYA, and how I eventually managed to overcome various issues to attain a perfect result (with the help of developers who knew what they were doing much better than I did!)",
		tags: ["2021","December","Dev musings","Advent calendar"],
	},
]