var item_tags = [
	["2020","2021","2022","2023","2024","2025"],
	["YAYA","AYA"],
	["Pure function"],
]

var item_details = [
	{
		name: "AI graph dialogue counter",
		release: "2023-06-02",
		latest: null,
		version: null,
		forevent: null,
		language: "YAYA",
		download: "AI_graph_dialogue_counter.txt",
		blurb: "A simple setup to output the count of outputs in a function to SSP's AI graph. This is useful if you've got a lot of word groups (\"envelopes\") or dialogue pools to count! There are many other things you can use the AI graph for as well, this is a pretty simple option.",
		tags: ["2023","YAYA"]
	},
	{
		name: "Auto anchor",
		release: "2021-11-23",
		latest: "2023-08-06",
		version: null,
		forevent: null,
		language: "YAYA",
		download: "Auto_anchor.txt",
		blurb: "This is a setup to make very basic anchors simple! It's meant for if you have, say, a bunch of anchors that have basic character explanations, and such. You add your names to a list, create corresponding \"Anchor.\" events, and then when you write the names in dialogue, you can write with an @ when you want it to be an anchor, or write without an @ if you just want to display the name as plain text!",
		tags: ["2021","YAYA"]
	},
	{
		name: "AutoPause",
		release: "2022-07-25",
		latest: "2024-06-30",
		version: null,
		forevent: null,
		language: "YAYA / AYA",
		download: "AutoPause.txt",
		blurb: "This handy function can automatically apply pause tags (\\w tags) to your dialogues! It takes a bit of getting used to, but it can make your scripts much cleaner and much faster to write! Just follow the instructions carefully, and make sure you know how to plan so that it doesn't make your menus wonky.",
		tags: ["2022","YAYA","AYA"]
	},
	{
		name: "BottomText",
		release: "2024-05-21",
		latest: null,
		version: null,
		forevent: null,
		language: "YAYA / AYA",
		download: "BottomText.txt",
		blurb: "A small set of events/functions for displaying text on the bottom of a balloon, no matter what balloon the user is using! There are some limitations, so be sure to read the instructions. This implementation is also intentionally kept simple, but it could definitely be expanded for use with more balloon sizes, etc., if need be!",
		tags: ["2024","YAYA"]
	},
	{
		name: "Capitalize",
		release: "2021-01-05",
		latest: "2024-03-20",
		version: null,
		forevent: null,
		language: "YAYA",
		download: "Capitalize.txt",
		blurb: "Capitalizes the first letter of whatever input you give it! This is useful if you want to, say, capitalize the output of a function. It's not really useful if you feed it a plain string. You can write it like %(Capitalize(food)) in your dialogue!",
		tags: ["2024","YAYA","Pure function"] //This probably is AYA also
	},
	{
		name: "Check surfaces",
		release: "2022-02-09",
		latest: "2023-08-06",
		version: null,
		forevent: null,
		language: "YAYA",
		download: "Check_surfaces.txt",
		blurb: "If you've got a ghost with multiple shells and can't guarantee they all have the same surfaces, this handy function will make it so that your ghost defaults to surface0 instead of disappearing! This is mainly intended for if someone else makes a shell for your ghost, but you continue to update it with new surfaces. There is also an SSP preferences setting to do this, but that relies on the user knowing about and setting that option.",
		tags: ["2022","YAYA"]
	},
	{
		name: "CreepyText",
		release: "2020-11-04",
		latest: "2021-01-05",
		version: null,
		forevent: null,
		language: "YAYA",
		download: "CreepyText.txt",
		blurb: "This text effect takes your text and splatters it all across the balloon, but slowly! And by that I mean, it types out the letters one at a time in random positions, with random pauses between them. Some of the parameters are adjustable.",
		tags: ["2020","Pure function"]
	},
	{
		name: "Daily dialogues",
		release: "2021-11-30",
		latest: "2023-08-05",
		version: null,
		forevent: null,
		language: "YAYA / AYA",
		download: "Daily_dialogues.txt",
		blurb: "This function is just a setup for if you wanted to have a set of dialogues (or something else) that is unique every day! I did this once for a ghost and it was a ton of work with not all that much reward, so I don't super recommend it honestly, but if you want to challenge yourself here you go!",
		tags: ["2021","YAYA","AYA"]
	},
	{
		name: "Deflicker",
		release: "2022-09-21",
		latest: null,
		version: null,
		forevent: null,
		language: "YAYA / AYA",
		download: "Deflicker.txt",
		blurb: "Ever notice that ghost menus tend to flicker when you click on stuff? I do! So I crafted this convoluted setup to fix it, and then packaged that into an easy-to-add module for your ghost. All you'll have to do is add \\![deflicker] to your menu script, and your flicker woes will disappear! Provided it's a menu that's suitable. If your menu displays dialogue before the rest shows up, or something along those lines, this won't help you.<br><br>If you're using AYA, you'll need to incorporate this into OnTranslate itself. In YAYA, simply add the function to your ghost, and it will work automatically!",
		tags: ["2022","YAYA","AYA"]
	},
	{
		name: "DisplayReal",
		release: "2023-09-04",
		latest: null,
		version: null,
		forevent: null,
		language: "YAYA",
		download: "DisplayReal.txt",
		blurb: "Want to display a real number (float) without all those annoying trailing 0s? This function can help! Note that this is for display purposes only, the result it returns is a string and not a number.",
		tags: ["2023","YAYA","Pure function"]
	},
	{
		name: "ErrorLog",
		release: "2022-06-04",
		latest: null,
		version: null,
		forevent: null,
		language: "YAYA",
		download: "ErrorLog.txt",
		blurb: "A debugging function that you can use to output information to SSP's error log! This just makes the process a bit simpler. Very useful if you've got a stubborn issue somewhere that seems to crop up whenever Tama is closed! You can have this silently logging information to the error log and check on it later, if you want. Or you can have it flag issues up immediately, and alert you with a notification!",
		tags: ["2022","YAYA"]
	},
	{
		name: "FormatLinks",
		release: "2021-11-20",
		latest: null,
		version: null,
		forevent: null,
		language: "YAYA",
		download: "FormatLinks.txt",
		blurb: "A function to simplify adding links to your right click menu, so that all you need to do is write an alternating list of labels and links. Makes things nice and tidy!",
		tags: ["2021","YAYA"]
	},
	{
		name: "GhostIsOpen & GhostIsInstalled",
		release: "2025-01-31",
		latest: null,
		version: null,
		forevent: null,
		language: "YAYA",
		download: "GhostIsOpen_GhostIsInstalled.txt",
		blurb: "A couple of functions for easily determining if a particular ghost is installed, or is currently open. Use it to comment on other ghosts, or whatever you feel like doing!<br><br>This may also be helpful if you're <a href='../guide/what_is_auto_data_convert.html'>transitioning a ghost off of AUTO_DATA_CONVERT</a>, since one of the things that tends to break in that conversion is old implementations of checking for other open ghosts that use a variable called ghostexlist. These functions will work with AUTO_DATA_CONVERT off!",
		tags: ["2025","YAYA"]
	},
	{
		name: "GroupDigits",
		release: "2025-06-20",
		latest: null,
		version: null,
		forevent: null,
		language: "YAYA",
		download: "GroupDigits.txt",
		blurb: "A function to convert integers or real numbers to a string with commas as thousands separators. For example, 1234567890 becomes 1,234,567,890.<br><br>Only supports comma separators for now! You can customize it if you want a different format, or I may consider adding the option for more formats in the future.",
		tags: ["2025","YAYA","Pure function"]
	},
	{
		name: "Holding Obsidian",
		release: "2020-11-04",
		latest: "2020-11-06",
		version: "v1.0.1",
		forevent: null,
		language: "YAYA",
		download: "https://www.mediafire.com/file/b9a2k87ikhwxdyr/How_To_Make_Your_Ghost_Hold_Obsidian_v1.0.1.zip/file",
		blurb: "A guide for getting your ghost to hold <a href='../ghost/dusty_and_obsidian.html'>Dusty's cat, Obsidian</a>! This is a rather old system and I've wanted to update it for years to use raiseother tags instead. I don't know that I'll ever do that at this point, unfortunately, but if you're looking to make a similar system, I highly recommend using raiseother and not using this method as an example! This way requires so much extra effort.<br><br>Please also note that you can add Obsidian as a dressup on your character, if you want to avoid having to add in checks for her everywhere. SmokyCinnamonroll did this with his ghost <a href='https://smokycinnamon.github.io/indifferentsorrel/tadora'>Tadora</a>!",
		tags: ["2020","YAYA"]
	},
	{
		name: "Idle between dialogues",
		release: "2023-09-13",
		latest: "2024-03-09",
		version: null,
		forevent: null,
		language: "YAYA",
		download: "Idle_between_dialogues.txt",
		blurb: "Have you ever noticed that most ghosts don't move between their dialogues, other than resetting to a default pose? For a lot of ghosts that's fine, but if you'd like yours to be a little more lively, this code will let them switch poses between dialogues! It even works if dialogues are completely turned off. I originally wrote this for <a href='../ghost/xanders_refuge.html'>Xander's Refuge</a>, and I think it does a lot to make him feel more organic.",
		tags: ["2023","YAYA"]
	},
	{
		name: "Interval Stacker",
		release: "2020-11-03",
		latest: "2021-01-17",
		version: "v2.0.5",
		forevent: null,
		language: "YAYA",
		download: "https://www.mediafire.com/file/pv3n99i7v8ervov/IntervalStacker_v2.0.5.zip/file",
		blurb: "This is a tool I made that helps with shell setups that use a lot of animations called by \\i[] tags! Note that in this tool, such animations are referred to as \"intervals\" even though that's not actually the right term. Currently this is distributed as a .dic file that you can add to your ghosts individually. It uses a SERIKO parser by <a href='https://levidre.github.io/'>Levidre</a>, though at the moment it only supports the old definition of SERIKO.",
		tags: ["2020","YAYA"]
	},
	{
		name: "IntToNumeral",
		release: "2022-05-13",
		latest: null,
		version: null,
		forevent: null,
		language: "YAYA / AYA",
		download: "IntToNumeral.txt",
		blurb: "A simple conversion from integer to roman numerals! I made this for <a href='../ghost/needle.html'>Needle</a> during Ghost Jam 2022, so that we could easily have it generate random roman numerals that are actually valid.",
		tags: ["2022","YAYA","AYA","Pure function"]
	},
	{
		name: "ISUPPER & ISLOWER",
		release: "2022-06-22",
		latest: null,
		version: null,
		forevent: null,
		language: "YAYA / AYA",
		download: "ISUPPER_ISLOWER.txt",
		blurb: "A pair of functions to quickly check if a given string is all uppercase or all lowercase!",
		tags: ["2022","YAYA","AYA","Pure function"]
	},
	{
		name: "leapyear",
		release: "2021-11-26",
		latest: null,
		version: null,
		forevent: null,
		language: "YAYA / AYA",
		download: "leapyear.txt",
		blurb: "This function well help you determine if it's a leapyear or not! You can check the current year, or send it a specific year to check as an argument!",
		tags: ["2021","YAYA","AYA"]
	},
	{
		name: "LetterCount",
		release: "2023-05-15",
		latest: null,
		version: null,
		forevent: null,
		language: "YAYA / AYA",
		download: "LetterCount.txt",
		blurb: "Counts the number of letters in a given string. For example, if you input the string \"ukagaka\" and search for \"a\", it will return 3. Made for the ghost <a href='../ghost/please_arrive_15_minutes_before_your_scheduled_interview_time.html'>Please arrive 15 minutes before your scheduled interview time</a> during Ghost Jam 2023!",
		tags: ["2023","YAYA","AYA","Pure function"]
	},
	{
		name: "LoopImage",
		release: "2022-11-07",
		latest: null,
		version: null,
		forevent: null,
		language: "YAYA / AYA",
		download: "LoopImage.txt",
		blurb: "A weird thing I wrote on a whim one time. If you want an animated image in your ghost's balloon, it may be able to help. It looks a little scary, but most of the options can be ignored if you don't need them!",
		tags: ["2022","YAYA","AYA","Pure function"]
	},
	{
		name: "Markdown processor",
		release: "2022-08-09",
		latest: "2022-08-26",
		version: "v1.0.2",
		forevent: null,
		language: "YAYA",
		download: "https://www.mediafire.com/file/lhvamfbysq2edo6/markdown_processor_v1.0.2.zip/file",
		blurb: "This is a .dic file that you can add to your ghost, which will allow you to use a rough markdown formatting for your dialogue! You can even set the tags to almost anything you want. It has a few quirks, like using | instead of \\ to escape tags, because of overlap with SakuraScript tags. But it can still be quite handy! Note that this makes use of my SakuraScooper function and comes bundled with it.<br><br>Changes for this file are available to see <a href='https://github.com/Zichqec/ukagaka/commits/main/function/markdown_processor.dic'>here</a>.",
		tags: ["2022","YAYA"]
	},
	{
		name: "Mock",
		release: "2021-01-05",
		latest: "2021-01-27",
		version: null,
		forevent: null,
		language: "YAYA / AYA",
		download: "Mock.txt",
		blurb: "This function will output text in MoCkCaSe! It can either do a strict alternating between upper and lowercase, or it can alternate randomly.",
		tags: ["2021","YAYA","AYA","Pure function"]
	},
	{
		name: "Music player",
		release: "2022-04-29",
		latest: "2025-04-22",
		version: "v2.0.3",
		forevent: null,
		language: "YAYA",
		download: "https://github.com/Zichqec/music_player/releases/latest",
		blurb: "This is an updated version of the music player in <a href='../ghost/flux.html'>FLUX</a>! This music player actually started all the way back in <a href='../ghost/lulo.html'>Lulo</a>, then got rewritten for FLUX, and then got overhauled again to be in its own .dic file to be added to other ghosts! Follow the instructions carefully, as there are some steps you need to take to integrate this with your ghost.<br><br>If you use my <a href='../template/simplicity_template.html'>Simplicity Template</a>, I have created a special file bundle you can apply to a fresh, unmodified copy of Simplicity in order to do the basic integration automatically. You can download it at the same place the music player file itself is downloaded from. Please read the instructions carefully.<br><br>If you use this code, please put a credit in your ghost's readme stating such! I worked very hard on this music player, it's a big thing with a lot of little functions and polish.<br><br>Changes to the music player can be tracked <a href='https://github.com/Zichqec/music_player/commits/main/music_player.dic'>here</a>.",
		tags: ["2022","YAYA"]
	},
	{
		name: "Needle poking repeatedly",
		release: "2024-12-17",
		latest: null,
		version: null,
		forevent: null,
		language: "YAYA",
		download: "Needle_poking_repeatedly.txt",
		blurb: "A bit of simple logic for the <a href='https://ukagakadreamteam.github.io/ukadoc/manual/list_shiori_event_ex.html#OnNeedlePoke'>OnNeedlePoke</a> event, to allow your ghost to react if the user has been pestering them repeatedly with Needle in a short timespan! Can also be used as a base to create similar functions, for things like repeated petting, pestering with a specific question, etc.",
		tags: ["2024","YAYA"]
	},
	{
		name: "NumSuffix",
		release: "2022-05-05",
		latest: "2025-06-12",
		version: null,
		forevent: null,
		language: "YAYA",
		download: "NumSuffix.txt",
		blurb: "Adds the appropriate suffix to any number you pass in. So 2 becomes 2nd, 11 becomes 11th, and 123 becomes 123rd.",
		tags: ["2022","YAYA","Pure function"]
	},
	{
		name: "OnRandomDressup",
		release: "2021-07-13",
		latest: "2024-05-20",
		version: null,
		forevent: null,
		language: "YAYA",
		download: "OnRandomDressup.txt",
		blurb: "If you have a lot of dressups, you might want a button to select some of them randomly. And that's just what this will do! This function will respect various options that dressups may have, like having a chance to pick multiple of a dressup category if the multiple option is specified.",
		tags: ["2021","YAYA"]
	},
	{
		name: "OnWander",
		release: "2020-11-04",
		latest: "2022-04-29",
		version: null,
		forevent: null,
		language: "YAYA",
		download: "OnWander.txt",
		blurb: "This set of functions will let your ghost wander around the screen to random places! They will respect the screen boundaries and always stay on the screen that they're currently on. I've made better movement code in <a href='../ghost/gallery_512.html'>Gallery 512</a> now, but it's a little tangled up in the jam mess of that ghost. At some point I'll clean that up and replace this one, though! This is quite old.",
		tags: ["2020","YAYA"]
	},
	{
		name: "Parallel",
		release: "2021-01-05",
		latest: null,
		version: null,
		forevent: null,
		language: "YAYA",
		download: "Parallel.txt",
		blurb: "This function lets multiple characters say different things at the same time. I made this bit of code because I couldn't get an old SAORI called parallel working. And then I finally figured out how to use SAORI-basic! But the output of that SAORI wasn't ideal to me because the more characters talked the more the text speed slowed down. So, I kept this, because this lets them all type at normal speed. The one downside is that this does not activate talk animations, but you can possibly mitigate that by adding in some \\i[] tags that call the talk animation.",
		tags: ["2021","YAYA"]
	},
	{
		name: "Pool",
		release: "2021-08-03",
		latest: null,
		version: null,
		forevent: null,
		language: "YAYA",
		download: "Pool.txt",
		blurb: "Boy have I got a story about this one. If you're on modern versions of YAYA, you have no need of this function. If you're on old versions of YAYA (sorry AYA, this won't work for you), then <a href='../blog/2021-12-12_advent_calendar_probabilities.html'>let me tell you about the probability problem and the lengths I went to to solve it</a>. I'm leaving this function up for anyone that can't or won't update their YAYA (but you <i>really should</i> unless you literally cannot), and for historical purposes. These days, you can simply use the pool or nonoverlap_pool modifiers on your dialogue pools to get the same effect way easier!",
		tags: ["2021","YAYA"]
	},
	{
		name: "RangeRand",
		release: "2023-06-19",
		latest: null,
		version: null,
		forevent: null,
		language: "YAYA / AYA",
		download: "RangeRand.txt",
		blurb: "A little function I wrote for <a href='../ghost/if_i_cant_have_shrimp_no_one_can.html'>If I can't have shrimp no one can</a>, during Idea Adoption Jam! Gets a pseudo random number within the specified range, and can even handle negative numbers! So for example, if you want to get a random number between 5 and 10, this makes that easy!",
		tags: ["2023","YAYA","AYA","Pure function"]
	},
	{
		name: "RoboText",
		release: "2025-07-28",
		latest: null,
		version: null,
		forevent: null,
		language: "YAYA",
		download: "RoboText.txt",
		blurb: "A function I wrote for <a href='../ghost/atm_machine.html'>ATM Machine</a>, to give the ATM dialogues a more robotic feel. This breaks up dialogue strings into small chunks (by default 3 characters long) and displays each chunk instantly with a small pause between.<br><br>It's a bit fiddly, you have to work around SakuraScript tags (and take extra steps to make it play nice with AutoPause if you're using that), but it's a neat text effect if you can get it working!",
		tags: ["2025","YAYA","Pure function"]
	},
	{
		name: "SakuraScooper",
		release: "2022-08-09",
		latest: null,
		version: "v1.0.0",
		forevent: null,
		language: "YAYA",
		download: "SakuraScooper.txt",
		blurb: "This function can be used to identify all the SakuraScript tags within a given string. What you do with that information is up to you! I made it for the purposes of being able to scrape SakuraScript tags out of strings, perform processing on the strings, and then put the SakuraScript tags back in intact. Note that it can run slowly if you give it strings with a lot of tags! (A lot meaning upwards of 100.)",
		tags: ["2022","YAYA"]
	},
	{
		name: "Shuffle",
		release: "2021-01-18",
		latest: null,
		version: null,
		forevent: null,
		language: "YAYA",
		download: "Shuffle.txt",
		blurb: "Do you need to shuffle the elements of an array, or the letters in a string? That's what this function will do! Simply feed it an array or a string, and if it's an array it'll spit it back out with the elements in a random order, and if it's a string, it'll spit it back out with the letters in a random order! Note that because of this, it only works with general purpose arrays, not simple arrays.",
		tags: ["2021","YAYA","Pure function"]
	},
	{
		name: "Simple Flags",
		release: "2021-01-15",
		latest: "2021-02-02",
		version: null,
		forevent: null,
		language: "YAYA",
		download: "Simple_Flags.txt",
		blurb: "This flag system is useful if you find yourself creating a lot of global variables for flags. The kinds of things that you only ever set to 1 or 0! Like if the user has discovered X secret about your ghost, or has played X minigame for the first time. This can cut down on the amount of global variables you have by simply storing them all in an array. And you can use any string as the name for a flag, to make it as descriptive as you like!",
		tags: ["2021","YAYA"]
	},
	{
		name: "StartsWith & EndsWith",
		release: "2022-03-30",
		latest: "2023-08-06",
		version: null,
		forevent: null,
		language: "YAYA / AYA",
		download: "StartsWith_EndsWith.txt",
		blurb: "A pair of functions for checking the start and end of a string! For example, you could check if a string begins with \"Mr.\" or \"https://\", or if it ends with \".txt\" or \"!\", etc.",
		tags: ["2022","YAYA","AYA","Pure function"]
	},
	{
		name: "TalkRateLabel",
		release: "2024-01-20",
		latest: "2024-05-20",
		version: null,
		forevent: null,
		language: "YAYA / AYA",
		download: "TalkRateLabel.txt",
		blurb: "Generates a nice label for your talk rate (like \"1 minute, 30 seconds\"), so that you don't need a stack of if checks in every menu where you want to display the current talk rate, and you don't have to write the labels by hand. It would also work well for things like a customizable talk rate!<br><br>While it is specifically keyed for talk rates, it is built to be easily customized and can be repurposed for other things.",
		tags: ["2024","YAYA","AYA"]
	},
	{
		name: "Update progress bar",
		release: "2021-12-02",
		latest: "2023-08-06",
		version: null,
		forevent: null,
		language: "YAYA / AYA",
		download: "Update_progress_bar.txt",
		blurb: "A progress bar for network updates. I don't recommend using this! Having these update events AT ALL aside from the error events will slow down your network updates DRASTICALLY. Like, 3x to 5x slow down, if I had to estimate. These events were made for a time when download speeds were much slower, but these days the time it takes to display the text (even if you use instant display!) makes it take a little extra time between each file, and it adds up quick unless your updates are small. But if you really want an update bar, this is a quick and clean setup!",
		tags: ["2021","YAYA","AYA"]
	},
	{
		name: "WearingDressup",
		release: "2024-02-24",
		latest: null,
		version: null,
		forevent: null,
		language: "YAYA",
		download: "WearingDressup.txt",
		blurb: "If you need quick and easy checks for if a character is wearing certain dressups, this function will do that for you! Note that this isn't the only way to check for dressups, so if you need something more complicated then you may have to write custom code.<br><br>Also note that this includes the event OnNotifyDressupInfo, so if you've already got that event, you may need to make modifications!",
		tags: ["2024","YAYA"]
	},
	{
		name: "Wobble",
		release: "2021-01-05",
		latest: null,
		version: null,
		forevent: null,
		language: "YAYA",
		download: "Wobble.txt",
		blurb: "This is a text effect to create weird, wobbly text! It can make the text go up and down, grow or strink, and changes cases randomly if you like! The text will go off the side of the balloon if it extends far enough, but it's a pretty fun effect regardless.",
		tags: ["2021","YAYA","Pure function"]
	},
	{
		name: "yearweek",
		release: "2021-11-26",
		latest: null,
		version: null,
		forevent: null,
		language: "YAYA / AYA",
		download: "yearweek.txt",
		blurb: "This function will tell you what week of the year it currently is! There is probably a smarter math way of doing this than what I've done here, but math isn't my strong suit and loops are! Maybe at some point I'll update this.",
		tags: ["2021","YAYA","AYA"]
	}
]