let shell_details = [

	{
		name: "A thousand thousand dots",
		goeswith: [Needle],
		release: "November 11th, 2023",
		latest: null,
		version: "v1.0.0",
		forevent: "Needle Day (11/11)",
		collaborators: null,
		content_warnings: null,
		download: "https://www.mediafire.com/file/wpgulz48ayt51zt/a_thousand_thousand_dots_v1.0.0.nar/file",
		blurb: "I started clicking around in my art program with a scatter brush, zoned out, and then like 15 minutes later I had a shell. Enjoy getting poked by dots."
	},
	{
		name: "After the rainfall",
		goeswith: [Hydrate],
		release: "August 20th, 2023",
		latest: null,
		version: "v1.0.0",
		forevent: "8/20 Hydrate Shell Jam 2023",
		collaborators: null,
		content_warnings: null,
		download: "https://www.mediafire.com/file/7ckaqxegdioyqvv/after_the_rainfall_v1.0.0.nar/file",
		blurb: "Do you want to drink your water off a leaf? Of course you do! This simple shell hangs out on the right side of your screen and that's about it."
	},
	{
		name: "Angrily Vibrating Flamingo",
		goeswith: [IfICantHaveShrimpNoOneCan],
		release: "June 23rd, 2024",
		latest: null,
		version: "v1.0.0",
		forevent: "National Pink Flamingo Day",
		collaborators: null,
		content_warnings: "Intense vibrating effects (toggleable)",
		download: "https://www.mediafire.com/file/x9bl69kdjrduy3z/angrily_vibrating_flamingo_v1.0.0.nar/file",
		blurb: "Have you ever wanted a flamingo so angry that it vibrates? Well now you can! And if you're sensitive to that kind of motion, you can toggle it off via dressups and enjoy a normal alternative shell."
	},
	{
		name: "ASCIIdle",
		goeswith: [Needle],
		release: "November 11th, 2024",
		latest: null,
		version: "v1.0.0",
		forevent: "Needle Day (11/11)",
		collaborators: null,
		content_warnings: null,
		download: "https://www.mediafire.com/file/j3fqxczcxty8bgv/asciidle_v1.0.0.nar/file",
		blurb: "A text-based needle for all your text-based needle needs! The text can be uppercase or lowercase, and the color can be black, white, or both!"
	},
	{
		name: "Ballpoint",
		goeswith: [Needle],
		release: "November 11th, 2024",
		latest: null,
		version: "v1.0.0",
		forevent: "Needle Day (11/11)",
		collaborators: null,
		content_warnings: null,
		download: "https://www.mediafire.com/file/d2wxbnkhw8bi23a/ballpoint_v1.0.0.nar/file",
		blurb: "A needle drawn with a ballpoint pen. Comes with 3 designs that can be switched between via dressups!"
	},
	{
		name: "Ballpoint Pen",
		goeswith: [Hydrate],
		release: "August 20th, 2022",
		latest: null,
		version: "v1.0.0",
		forevent: "8/20 Hydrate Shell Jam 2022",
		collaborators: null,
		content_warnings: null,
		download: "https://www.mediafire.com/file/1ea756h3arqa7vs/ballpoint_pen_zi_v1.0.0.nar/file",
		blurb: "A ballpoint pen shell for Hydrate, made on a whim at the end of the jam! It's inspired by what was one of my favorite pens at my job at the time. Who wouldn't want to drink pen ink!? (Don't drink ink.)"
	},
	{
		name: "Birthday Needle",
		goeswith: [Needle],
		release: "January 7th, 2024",
		latest: null,
		version: "v1.0.0",
		forevent: "Perseverence Day",
		collaborators:
		[
			Galla
		],
		content_warnings: null,
		download: "https://www.mediafire.com/file/encn6b68y41o6bx/birthday_needle_v1.0.0.nar/file",
		blurb: "A celebratory Needle drawn by Galla, and decorated with candle dressups by me, in commemoration of yet another lap around the sun. A personal high score!"
	},
	{
		name: "Cavatappi",
		goeswith: [Noodle],
		release: "September 24th, 2023",
		latest: null,
		version: "v1.0.0",
		forevent: "Etc. Jam 2023",
		collaborators: null,
		content_warnings: null,
		download: "https://www.mediafire.com/file/3mtcvd07vdy4hli/cavatappi_zi_v1.0.0.nar/file",
		blurb: "Noodle in cavatappi form! Made during Etc. Jam 2023, since I had more time than expected at the end. Comes in all the same colors as the original Noodle shell!"
	},
	{
		name: "Cibus",
		goeswith: [FLUX,FLELE],
		release: "October 9th, 2020",
		latest: "May 12th, 2021",
		version: "v2.0.0",
		forevent: null,
		collaborators: null,
		content_warnings: null,
		download: "https://www.mediafire.com/file/h985pm693slaqn3/cibus_v2.0.0.nar/file",
		blurb: "Cibus is an OC of mine, and she likes to sing! I originally made her as a FLELE shell to get more comfortable with SERIKO, and then when I made FLUX, I decided to add some custom dialogue and such for her as a test run of the system. The shell doesn't really explain anything about her, it's all a bit vague and mysterious."
	},
	{
		name: "Close-Up View",
		goeswith: [Needle],
		release: "November 11th, 2022",
		latest: null,
		version: "v1.0.0",
		forevent: "Needle Day (11/11)",
		collaborators: null,
		content_warnings: null,
		download: "https://www.mediafire.com/file/ydjbqcpu6229u3m/close_up_view_v1.0.0.nar/file",
		blurb: "Released for Needle Day on 11/11, this massive shell clocks in at a canvas size of 5000x5030! If you really want to inspect Needle in great detail, this is the shell for you!<br><br>Note: SSP may struggle to run this shell, and even crash. You're on your own if it does!"
	},
	{
		name: "Colored Pencils",
		goeswith: [Needle],
		release: "November 11th, 2023",
		latest: null,
		version: "v1.0.0",
		forevent: "Needle Day (11/11)",
		collaborators: null,
		content_warnings: null,
		download: "https://www.mediafire.com/file/1pehzcs475gmuea/colored_pencils_v1.0.0.nar/file",
		blurb: "A simple colored pencil needle! It has a bit of a blue hue to it, since my gray pencils are cool grays. The frosty edges are a feature not a bug. They're part of the Needle style :sparkles:"
	},
	{
		name: "Conchiglie",
		goeswith: [Noodle],
		release: "September 24th, 2023",
		latest: null,
		version: "v1.0.0",
		forevent: "Etc. Jam 2023",
		collaborators: null,
		content_warnings: null,
		download: "https://www.mediafire.com/file/lxnumg24cvsiwi3/conchiglie_zi_v1.0.0.nar/file",
		blurb: "Noodle in conchiglie form! Made during Etc. Jam 2023, since I had more time than expected at the end. Comes in all the same colors as the original Noodle shell!"
	},
	{
		name: "Diamond Eye",
		goeswith: [Needle],
		release: "May 26th, 2022",
		latest: null,
		version: "v1.0.0",
		forevent: null,
		collaborators: null,
		content_warnings: null,
		download: "https://www.mediafire.com/file/e5mb26kvfgt5g8x/diamond_eye_v1.0.0.nar/file",
		blurb: "An alternative shell made for Needle, with soft shading. It's very typical of my style at the time! This was the first Needle shell I made, not long after Needle was released."
	},
	{
		name: "Expensive Needle",
		goeswith: [Needle],
		release: "November 11th, 2024",
		latest: null,
		version: "v1.0.0",
		forevent: "Needle Day (11/11)",
		collaborators:
		[
			Galla
		],
		content_warnings: null,
		download: "https://www.mediafire.com/file/hx039cguaqkjsmq/expensive_needle_v1.0.0.nar/file",
		blurb: "The most expensive needle you'll ever see! Buy now while you can! Comes with 17 different designs and 3 levels of sparkliness (or no sparkles at all, if you prefer)."
	},
	{
		name: "Farfalle",
		goeswith: [Noodle],
		release: "September 24th, 2023",
		latest: null,
		version: "v1.0.0",
		forevent: "Etc. Jam 2023",
		collaborators: null,
		content_warnings: null,
		download: "https://www.mediafire.com/file/dvus956q6b5nlp0/farfalle_zi_v1.0.0.nar/file",
		blurb: "Noodle in farfalle form! Made during Etc. Jam 2023, since I had more time than expected at the end. Comes in all the same colors as the original Noodle shell!"
	},
	{
		name: "Fineliners",
		goeswith: [Needle],
		release: "November 11th, 2024",
		latest: null,
		version: "v1.0.0",
		forevent: "Needle Day (11/11)",
		collaborators: null,
		content_warnings: null,
		download: "https://www.mediafire.com/file/g67r62rwuocmyky/fineliners_v1.0.0.nar/file",
		blurb: "A needle drawn with every color of fineliner I currently own! Switch between colors with dressups."
	},
	{
		name: "FLUX",
		goeswith: [FLUX,FLELE],
		release: "May 12th, 2021",
		latest: null,
		version: "v1.0.0",
		forevent: null,
		collaborators: null,
		content_warnings: null,
		download: "https://www.mediafire.com/file/5noi6l85a7xn06r/flux_shell_standalone_v1.0.0.nar/file",
		blurb: "A standalone version of the FLUX master shell! FLUX the character is actually separate from FLUX the music player system. This release exists so that you can use this shell with FLELE, if you prefer! This shell comes bundled with FLUX, and has custom dialogue, though it's all simply music notes. When playing music, he'll bob his head and use holographic synthesizers."
	},
	{
		name: "Glitchy Needle",
		goeswith: [Needle],
		release: "November 11th, 2024",
		latest: null,
		version: "v1.0.0",
		forevent: "Needle Day (11/11)",
		collaborators: null,
		content_warnings: "Flashing/jittering, sudden movements",
		download: "https://www.mediafire.com/file/d1kvybo18b5rfpe/glitchy_needle_v1.0.0.nar/file",
		blurb: "An entirely normal needle which has nothing strange about it. Strange happenings can most definitely not be controlled via dressups."
	},
	{
		name: "Gourmet Ravioli",
		goeswith: [FLUX,FLELE,Hydrate,Noodle,Presentable_Can],
		release: "October 26th, 2023",
		latest: "November 5th, 2023",
		version: "v1.0.1",
		forevent: null,
		collaborators: null,
		content_warnings: null,
		download: "https://www.mediafire.com/file/wlumv0c7wutalon/gourmet_ravioli_v1.0.1.nar/file",
		blurb: "A shell of a can of gourmet ravioli, lovingly based on the <a href=\"https://www.youtube.com/watch?v=0m-wBGGIBPo\">album art</a> of <a href=\"https://www.youtube.com/watch?v=6ZIogYd0gSo\">Gourmet Ravioli</a>, by First of October! This shell is made to go with 5 different ghosts, including hotspots for FLUX, FLELE, and Presentable Can! It also has dressups to suit Noodle. And who wouldn't want to get their hydration via canned ravioli!? This shell has it all!"
	},
	{
		name: "Graphite",
		goeswith: [Needle],
		release: "November 11th, 2023",
		latest: null,
		version: "v1.0.0",
		forevent: "Needle Day (11/11)",
		collaborators: null,
		content_warnings: null,
		download: "https://www.mediafire.com/file/ffvk7z6c8op7sfx/graphite_v1.0.0.nar/file",
		blurb: "Effectively 11 Needle shells in 1! For ultimate pointy potential. This shell features 11 designs done with a mechanical pencil. Basically, I had to try it 11 times before I got one that I liked. My favorite one is the one you see in the thumbnail here! I figured I may as well include the others as dressups to add more variety."
	},
	{
		name: "Inkdle",
		goeswith: [Needle],
		release: "November 11th, 2023",
		latest: null,
		version: "v1.0.0",
		forevent: "Needle Day (11/11)",
		collaborators: null,
		content_warnings: null,
		download: "https://www.mediafire.com/file/8bcsiay43uy8r5a/inkdle_v1.0.0.nar/file",
		blurb: "A simple inked needle, with an additional dressup that I made by mistake and then ended up really liking. Perfect for your black and white Needle needs."
	},
	{
		name: "Leaking from somewhere",
		goeswith: [Hydrate],
		release: "August 20th, 2024",
		latest: null,
		version: "v1.0.0",
		forevent: "8/20 Hydrate Shell Jam 2024",
		collaborators: null,
		content_warnings: null,
		download: "https://www.mediafire.com/file/mf10z1f6lgvlt7y/leaking_from_somewhere_v1.0.0.nar/file",
		blurb: "Uh oh, better get a bucket! This shell endlessly drips down from the top of your monitor, and may be useful if you want to keep Hydrate out of the way. Use dressups to add additional drips, and to change the liquid!"
	},
	{
		name: "Macaroni",
		goeswith: [Noodle],
		release: "September 24th, 2023",
		latest: null,
		version: "v1.0.0",
		forevent: "Etc. Jam 2023",
		collaborators: null,
		content_warnings: null,
		download: "https://www.mediafire.com/file/co7zxeiwpkdiv54/macaroni_zi_v1.0.0.nar/file",
		blurb: "Noodle in macaroni form! Made during Etc. Jam 2023, since I had more time than expected at the end. Comes in all the same colors as the original Noodle shell!"
	},
	{
		name: "Markers",
		goeswith: [Needle],
		release: "November 11th, 2023",
		latest: null,
		version: "v1.0.0",
		forevent: "Needle Day (11/11)",
		collaborators: null,
		content_warnings: null,
		download: "https://www.mediafire.com/file/waxf3jq8vlfcqs2/markers_v1.0.0.nar/file",
		blurb: "I drew Galla some gift art needles and colored them with marker, and then I figured, hey why not make a shell out of them? So I did. Happy Needle, Galla. Use dressups to change between the three designs."
	},
	{
		name: "Maybe a Tornado",
		goeswith: [Needle],
		release: "November 11th, 2023",
		latest: null,
		version: "v1.0.0",
		forevent: "Needle Day (11/11)",
		collaborators: null,
		content_warnings: null,
		download: "https://www.mediafire.com/file/d93cx0uot9c4bar/maybe_a_tornado_v1.0.0.nar/file",
		blurb: "Scribbles like this always look like tornadoes to me. Anyways it's vaguely needle-shaped so it counts. Can't say I'd want to sew with it though! It has also been described as \"fluffy\", but be warned that it is still pointy."
	},
	{
		name: "Metal Bottle",
		goeswith: [Hydrate],
		release: "August 20th, 2022",
		latest: null,
		version: "v1.0.0",
		forevent: null,
		collaborators: null,
		content_warnings: null,
		download: "https://www.mediafire.com/file/lahs1kuwx7nriat/metal_bottle_v1.0.0.nar/file",
		blurb: "A metal bottle, based on one I actually own! It comes with a lot of dressups that let you customize your cap color and bottle design. I had this shell in development for a long time, and I finally released it just before the start of the first 8/20 Hydrate Shell Jam. (I couldn't live with myself if I had worked on this shell for so long, and then Syringe ended up being my first released Hydrate shell...!)"
	},
	{
		name: "Moneydle",
		goeswith: [Needle],
		release: "November 11th, 2024",
		latest: null,
		version: "v1.0.0",
		forevent: "Needle Day (11/11)",
		collaborators: null,
		content_warnings: null,
		download: "https://www.mediafire.com/file/0hf59etg5mehacd/moneydle_v1.0.0.nar/file",
		blurb: "Needlebucks, for all your money needs! Not legal tender for any debts, public or private. Use dressups to un-scrunch."
	},
	{
		name: "Needly Accurate Angle",
		goeswith: [Needle],
		release: "November 11th, 2024",
		latest: null,
		version: "v1.0.0",
		forevent: "Needle Day (11/11)",
		collaborators: null,
		content_warnings: null,
		download: "TEMP",
		blurb: "FEAR NOT MORTAL. It's just a handmade gift that exists in the real world, brought into the digital realm so we can all benefit. Enjoy :)"
	},
	{
		name: "Old Beans",
		goeswith: [Hydrate,Presentable_Can],
		release: "October 27th, 2023",
		latest: null,
		version: "v1.0.0",
		forevent: null,
		collaborators: null,
		content_warnings: null,
		download: "https://www.mediafire.com/file/3yyjs7f53vufl7i/old_beans_v1.0.0.nar/file",
		blurb: "A shell I drew in 2021 for Hydrate, and then never finished. Released towards the end of 2023 just to have it out there! I also added a hotspot so it can be used with Presentable Can too. And a neat tiling bean pattern in the owner draw menu! Get some beans today."
	},
	{
		name: "Penne",
		goeswith: [Noodle],
		release: "September 24th, 2023",
		latest: null,
		version: "v1.0.0",
		forevent: "Etc. Jam 2023",
		collaborators: null,
		content_warnings: null,
		download: "https://www.mediafire.com/file/oltfnnvqkyromvo/penne_zi_v1.0.0.nar/file",
		blurb: "Noodle in penne form! Made during Etc. Jam 2023, since I had more time than expected at the end. Comes in all the same colors as the original Noodle shell!"
	},
	{
		name: "Rotini",
		goeswith: [Noodle],
		release: "September 24th, 2023",
		latest: null,
		version: "v1.0.0",
		forevent: "Etc. Jam 2023",
		collaborators: null,
		content_warnings: null,
		download: "https://www.mediafire.com/file/zd2rd6w5oh62sun/rotini_zi_v1.0.0.nar/file",
		blurb: "Noodle in rotini form! Made during Etc. Jam 2023, since I had more time than expected at the end. Comes in all the same colors as the original Noodle shell!"
	},
	{
		name: "Safety Needle",
		goeswith: [Needle],
		release: "November 11th, 2023",
		latest: null,
		version: "v1.0.0",
		forevent: "Needle Day (11/11)",
		collaborators: null,
		content_warnings: null,
		download: "https://www.mediafire.com/file/855l8tx04m2uo67/safety_needle_v1.0.0.nar/file",
		blurb: "A soft crochet needle made of plastic, with additional strings for decoration. There are 11 plastic colors, 11 string styles, and 11 colors for the strings! I'm not terribly good at math, but from my dodgy calculations it came out to over 240k combinations of dressups for this shell."
	},
	{
		name: "Spigot",
		goeswith: [Hydrate],
		release: "August 20th, 2024",
		latest: null,
		version: "v1.0.0",
		forevent: "8/20 Hydrate Shell Jam 2024",
		collaborators: null,
		content_warnings: null,
		download: "https://www.mediafire.com/file/x6kmi9k662g272s/spigot_v1.0.0.nar/file",
		blurb: "Who has time to run inside for a drink of water? Not me! But hey, the spigot's right there...<br><br>Comes with several spigot colors, various liquids, and you can control how far open the spigot is!"
	},
	{
		name: "Starset Messenger",
		goeswith: [FLUX,FLELE],
		release: "October 24th, 2021",
		latest: null,
		version: "v1.0.0",
		forevent: null,
		collaborators: null,
		content_warnings: null,
		download: "https://www.mediafire.com/file/y9egbvw67lgg4j8/starset_messenger_v1.0.0.nar/file",
		blurb: "Do you love Starset? Me too! That's why I made this Starset Messenger shell, to delight you by playing space songs on his space bass. When playing songs that are recognized as Starset, he will display various symbols from the band on his visor! If it's a song that has a specific symbol, he'll display that one in particular! By the way, if you look closely, the stars on his visor twinkle.<br><br>Note: this shell has been deliberately designed to not resemble any particular member of the band. He's his own thing!"
	},
	{
		name: "Syringe",
		goeswith: [Hydrate,Needle],
		release: "August 20th, 2022",
		latest: null,
		version: "v1.0.0",
		forevent: "8/20 Hydrate Shell Jam 2022",
		collaborators: null,
		content_warnings: null,
		download: "https://www.mediafire.com/file/8mteq41rnfmjt0w/syringe_zi_v1.0.0.nar/file",
		blurb: "A shell for both Hydrate and Needle! I thought that would be cool and fun, but you would not believe the consternation this has caused me figuring out how to categorize this dang thing! I like it a lot though, it's very silly, and it has a nice variety of dressups for needle length and the color of the liquid inside. Use it for whichever ghost you prefer, or both at once. What could go wrong, confusing your drink reminder with Needle!"
	},
	{
		name: "Tiered Bowls",
		goeswith: [Hydrate],
		release: "August 20th, 2023",
		latest: null,
		version: "v1.0.0",
		forevent: "8/20 Hydrate Shell Jam 2023",
		collaborators: null,
		content_warnings: null,
		download: "https://www.mediafire.com/file/jwqbrgb2ek7qi1a/tiered_bowls_v1.0.0.nar/file",
		blurb: "A tiered bowl water feature! Use a dressup to turn the water on or off. This shell hangs from the ceiling, which may be useful to keep it tucked out of the way!"
	},
	{
		name: "Tiny Pokey Pixels",
		goeswith: [Needle],
		release: "November 11th, 2022",
		latest: null,
		version: "v1.0.0",
		forevent: "Needle Day (11/11)",
		collaborators: null,
		content_warnings: null,
		download: "https://www.mediafire.com/file/38vapawmmy6fotb/tiny_pokey_pixels_v1.0.0.nar/file",
		blurb: "Released for Needle Day on 11/11, this tiny shell only has a canvas size of 16x16 pixels! If you're not careful, you may very well lose it on your desktop. Watch out, those pixels are pointy!"
	},
	{
		name: "Tuxeedle",
		goeswith: [Needle],
		release: "January 1st, 2024",
		latest: null,
		version: "v1.0.0",
		forevent: "mine and Galla's dev-wedding",
		collaborators: null,
		content_warnings: null,
		download: "https://www.mediafire.com/file/0obv5xn9kgkkar0/tuxeedle_v1.0.0.nar/file",
		blurb: "A shell made to officiate and commemorate mine and Galla's dev-wedding!  If you know you know. Comes with some additional dressups!"
	},
	{
		name: "Twemoji",
		goeswith: [Needle],
		release: "May 26th, 2022",
		latest: null,
		version: "v1.0.0",
		forevent: null,
		collaborators: null,
		content_warnings: null,
		download: "https://www.mediafire.com/file/28o2p3hzh31pv0c/twemoji_v1.0.0.nar/file",
		blurb: "A shell made with the :sewing_needle: emoji from the open source <a href='https://github.com/jdecked/twemoji'>Twemoji</a> set! There's not much to say here, I just like the look of Twemoji's sewing needle and figured it would be fun to have as an option."
	},
	{
		name: "Upholstery Needle",
		goeswith: [Needle],
		release: "November 11th, 2024",
		latest: null,
		version: "v1.0.0",
		forevent: "Needle Day (11/11)",
		collaborators: null,
		content_warnings: null,
		download: "https://www.mediafire.com/file/rdteq44d41cfu9s/upholstery_needle_v1.0.0.nar/file",
		blurb: "Did you know there are curved needles? You do now! Possibly one of the gnarliest needles in existence."
	},
	{
		name: "Wobbly Mouse Art",
		goeswith: [Needle],
		release: "November 11th, 2023",
		latest: null,
		version: "v1.0.0",
		forevent: "Needle Day (11/11)",
		collaborators: null,
		content_warnings: null,
		download: "https://www.mediafire.com/file/03be1pe4ihuw5wb/wobbly_mouse_art_v1.0.0.nar/file",
		blurb: "This is just a little Needle doodle I did on a whim at one point. And then I thought it was cute and decided it could stay."
	},
	{
		name: "X-ray",
		goeswith: [Needle],
		release: "November 11th, 2024",
		latest: null,
		version: "v1.0.0",
		forevent: "Needle Day (11/11)",
		collaborators: null,
		content_warnings: null,
		download: "https://www.mediafire.com/file/fx3quca9oxarhm0/x-ray_v1.0.0.nar/file",
		blurb: "Needle went in for a checkup and got this cool x-ray. Look at all those strong, healthy bones, ready to stab stab poke poke!"
	}
]